apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: matrixctrl
  labels:
    {{- include "matrixctrl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: matrixctrl
subjects:
  - kind: ServiceAccount
    name: matrixctrl
    namespace: matrixctrl
