apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrixctrl.secretName" . }}
  namespace: matrixctrl
  labels:
    {{- include "matrixctrl.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  {{- if .Values.secrets.adminPassword }}
  admin-password: {{ .Values.secrets.adminPassword | quote }}
  {{- end }}
  {{- if .Values.oidc.enabled }}
  oidc-client-id: {{ .Values.oidc.clientId | quote }}
  oidc-client-secret: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
