/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemRouteImport } from './routes/system'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksIndexRouteImport } from './routes/hooks/index'
import { Route as HelmIndexRouteImport } from './routes/helm/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as HooksIdRouteImport } from './routes/hooks/$id'
import { Route as HelmUpgradeRouteImport } from './routes/helm/upgrade'
import { Route as HelmHistoryRouteImport } from './routes/helm/history'
import { Route as ConfigHistoryRouteImport } from './routes/config/history'
import { Route as ConfigSliceRouteImport } from './routes/config/$slice'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksIndexRoute = HooksIndexRouteImport.update({
  id: '/hooks/',
  path: '/hooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelmIndexRoute = HelmIndexRouteImport.update({
  id: '/helm/',
  path: '/helm/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksIdRoute = HooksIdRouteImport.update({
  id: '/hooks/$id',
  path: '/hooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HelmUpgradeRoute = HelmUpgradeRouteImport.update({
  id: '/helm/upgrade',
  path: '/helm/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const HelmHistoryRoute = HelmHistoryRouteImport.update({
  id: '/helm/history',
  path: '/helm/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigHistoryRoute = ConfigHistoryRouteImport.update({
  id: '/config/history',
  path: '/config/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigSliceRoute = ConfigSliceRouteImport.update({
  id: '/config/$slice',
  path: '/config/$slice',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/system': typeof SystemRoute
  '/auth/login': typeof AuthLoginRoute
  '/config/$slice': typeof ConfigSliceRoute
  '/config/history': typeof ConfigHistoryRoute
  '/helm/history': typeof HelmHistoryRoute
  '/helm/upgrade': typeof HelmUpgradeRoute
  '/hooks/$id': typeof HooksIdRoute
  '/config/': typeof ConfigIndexRoute
  '/helm/': typeof HelmIndexRoute
  '/hooks/': typeof HooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/system': typeof SystemRoute
  '/auth/login': typeof AuthLoginRoute
  '/config/$slice': typeof ConfigSliceRoute
  '/config/history': typeof ConfigHistoryRoute
  '/helm/history': typeof HelmHistoryRoute
  '/helm/upgrade': typeof HelmUpgradeRoute
  '/hooks/$id': typeof HooksIdRoute
  '/config': typeof ConfigIndexRoute
  '/helm': typeof HelmIndexRoute
  '/hooks': typeof HooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/system': typeof SystemRoute
  '/auth/login': typeof AuthLoginRoute
  '/config/$slice': typeof ConfigSliceRoute
  '/config/history': typeof ConfigHistoryRoute
  '/helm/history': typeof HelmHistoryRoute
  '/helm/upgrade': typeof HelmUpgradeRoute
  '/hooks/$id': typeof HooksIdRoute
  '/config/': typeof ConfigIndexRoute
  '/helm/': typeof HelmIndexRoute
  '/hooks/': typeof HooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/system'
    | '/auth/login'
    | '/config/$slice'
    | '/config/history'
    | '/helm/history'
    | '/helm/upgrade'
    | '/hooks/$id'
    | '/config/'
    | '/helm/'
    | '/hooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/system'
    | '/auth/login'
    | '/config/$slice'
    | '/config/history'
    | '/helm/history'
    | '/helm/upgrade'
    | '/hooks/$id'
    | '/config'
    | '/helm'
    | '/hooks'
  id:
    | '__root__'
    | '/'
    | '/system'
    | '/auth/login'
    | '/config/$slice'
    | '/config/history'
    | '/helm/history'
    | '/helm/upgrade'
    | '/hooks/$id'
    | '/config/'
    | '/helm/'
    | '/hooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SystemRoute: typeof SystemRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ConfigSliceRoute: typeof ConfigSliceRoute
  ConfigHistoryRoute: typeof ConfigHistoryRoute
  HelmHistoryRoute: typeof HelmHistoryRoute
  HelmUpgradeRoute: typeof HelmUpgradeRoute
  HooksIdRoute: typeof HooksIdRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  HelmIndexRoute: typeof HelmIndexRoute
  HooksIndexRoute: typeof HooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/': {
      id: '/hooks/'
      path: '/hooks'
      fullPath: '/hooks/'
      preLoaderRoute: typeof HooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helm/': {
      id: '/helm/'
      path: '/helm'
      fullPath: '/helm/'
      preLoaderRoute: typeof HelmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/$id': {
      id: '/hooks/$id'
      path: '/hooks/$id'
      fullPath: '/hooks/$id'
      preLoaderRoute: typeof HooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helm/upgrade': {
      id: '/helm/upgrade'
      path: '/helm/upgrade'
      fullPath: '/helm/upgrade'
      preLoaderRoute: typeof HelmUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helm/history': {
      id: '/helm/history'
      path: '/helm/history'
      fullPath: '/helm/history'
      preLoaderRoute: typeof HelmHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/history': {
      id: '/config/history'
      path: '/config/history'
      fullPath: '/config/history'
      preLoaderRoute: typeof ConfigHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/$slice': {
      id: '/config/$slice'
      path: '/config/$slice'
      fullPath: '/config/$slice'
      preLoaderRoute: typeof ConfigSliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SystemRoute: SystemRoute,
  AuthLoginRoute: AuthLoginRoute,
  ConfigSliceRoute: ConfigSliceRoute,
  ConfigHistoryRoute: ConfigHistoryRoute,
  HelmHistoryRoute: HelmHistoryRoute,
  HelmUpgradeRoute: HelmUpgradeRoute,
  HooksIdRoute: HooksIdRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  HelmIndexRoute: HelmIndexRoute,
  HooksIndexRoute: HooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
